### ISSUE TITLE
OAuthStrategy requires a consumerKey option

### ISSUE THREAD

**Issue by graphixx** [watson-developer-cloud/personality-insights-nodejs#182]
I set the TWITTER_CONSUMER_KEY and the TWITTER_CONSUMER_SECRET in the .env
I try to deploy in CPANEL and the Passenger application server show me the error:
```
i18n module initialized. Default locale: en
/home/municiondigital/ibmwatson/node_modules/passport-oauth1/lib/strategy.js:83
  if (!options.consumerKey) { throw new TypeError('OAuthStrategy requires a consumerKey option'); }
                              ^

TypeError: OAuthStrategy requires a consumerKey option
    at Strategy.OAuthStrategy (/home/municiondigital/ibmwatson/node_modules/passport-oauth1/lib/strategy.js:83:37)
    at new Strategy (/home/municiondigital/ibmwatson/node_modules/passport-twitter/lib/strategy.js:53:17)
    at Object.<anonymous> (/home/municiondigital/ibmwatson/config/passport.js:32:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Module.require (/opt/cpanel/ea-ruby24/root/usr/share/passenger/helper-scripts/node-loader.js:80:25)
```

**Comment by germanattanasio** [comment]
You need the following variables
```
TWITTER_ACCESS_TOKEN=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TOKEN_SECRET=
```
